<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="MBS_MR01_AS_SecuringProcess" Id="{2b1534eb-d527-431b-9fb5-33274cbac8f1}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'OPC.UA.DA.JobMethod' := 'JobMethode_SecuringProcess'}
FUNCTION_BLOCK MBS_MR01_AS_SecuringProcess
VAR
	AlwaysTrue : BOOL := TRUE;
	// Used for debugging purposes to display InputArguments of method call
	MethodCall_SecuringProcess : BOOL := FALSE; // used to store InputArg "MethodCall" from Start() method
	ResetMethodCall	: BOOL := FALSE;	
	SecuringTime : TIME;	//Time for Securing the Workpiece
	SecuringProcessingTime : TIME; //Two Times for Securing the Workpiece (for Secure and Release) + HardeningProcessingTime
	callCounterStart : ULINT; // counts how many times the Start() method has been called
	callCounterCheckState : ULINT; // counts how many times the CheckState() method has been called
	callCounterAbort : ULINT; // counts how many times the Abort() method has been called
	
	// Variables to determine if a job has been started (Start() method has been called) or finished
	jobRunning : BOOL;
	jobFinished : BOOL;

	// State machine variable
	state : UDINT;
	
	//Variablen des FBs
	MBS_MR01_SecuringProcess : SecuringWorkpiece;
END_VAR
	
VAR_INPUT
	ESS: BOOL;
	TouchSensor_01 : BOOL;
	AutomaticMode: BOOL;
END_VAR

VAR_OUTPUT
	DO_SecuringProcessCompressorMR01_01 : BOOL;
	DO_SecuringProcessValveMR01_02 : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Fbd"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"EXECUTE"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">1963L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"AlwaysTrue"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">469L</v>
                          </o>
                          <v n="Id">468L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">None</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <o n="STSnippet" t="STSnippet">
                        <o n="STSnippet" t="STImplementationObject">
                          <o n="TextDocument" t="TextDocument">
                            <v n="TextBlobForSerialisation">"CASE state OF
	0:
		IF jobRunning THEN
			state := state + 1;
		END_IF
		
	1:
		IF ResetMethodCall THEN
			jobRunning := FALSE;
			jobFinished := TRUE;
			state := 0;
			MethodCall_SecuringProcess := FALSE;
		END_IF
		
END_CASE
"</v>
                            <n n="LineInfoPersistence" />
                          </o>
                        </o>
                        <v n="Id">1979L</v>
                      </o>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">true</v>
                      <v n="Id">1980L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">30L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"DO_SecuringProcessCompressorMR01_01"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">2003L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"SecuringWorkpiece"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"MBS_MR01_SecuringProcess"</v>
                          <v n="Type">"SecuringWorkpiece"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">2007L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">"DO_SecuringProcessValveMR01_02"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1995L</v>
                            </o>
                            <o>
                              <v n="Operand">"ResetMethodCall"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1996L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"MethodCall_SecuringProcess"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1677L</v>
                            </o>
                            <v n="Id">1676L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"ESS"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1902L</v>
                            </o>
                            <v n="Id">1901L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">2010L</v>
                            </o>
                            <v n="Id">2009L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"TouchSensor_01"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1998L</v>
                            </o>
                            <v n="Id">1997L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"SecuringTime"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">2000L</v>
                            </o>
                            <v n="Id">1999L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"SecuringProcessingTime"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">2002L</v>
                            </o>
                            <v n="Id">2001L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"AutomaticMode"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">1938L</v>
                            </o>
                            <v n="Id">1937L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>MethodCall</v>
                            <v>EmergencyStopSignal</v>
                            <v>InitStateDrive_Input</v>
                            <v>DI01</v>
                            <v>TON_Time_Securing</v>
                            <v>TON_Time_SecuringProcess</v>
                            <v>OperatingMode</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>TIME</v>
                            <v>TIME</v>
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>DigitalOutputControl_01</v>
                            <v>DigitalOutputControl_02</v>
                            <v>ResetMethodCall</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">2008L</v>
                      </o>
                      <v n="Id">2004L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">973L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="STImplementationObject">{3b83b776-fb25-43b8-99f2-3c507c9143fc}</Type>
            <Type n="String">System.String</Type>
            <Type n="STSnippet">{b2131366-6917-4304-87a9-64c0585560a8}</Type>
            <Type n="TextDocument">{f3878285-8e4f-490b-bb1b-9acbb7eb04db}</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Method Name="Abort" Id="{0da98f48-656c-4805-89ab-798246fcb813}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable' := '1'}
METHOD Abort : HRESULT
VAR_INPUT
	hdl : UDINT; // Do not change, used by server.
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[callCounterAbort := callCounterAbort + 1;]]></ST>
      </Implementation>
    </Method>
    <Method Name="CheckState" Id="{d74b50de-72c0-484f-b3a6-e7c7388e8f18}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable' := '1'}
METHOD CheckState : HRESULT
VAR_INPUT
	hdl : UDINT; // Do not change, used by server.
END_VAR
VAR_OUTPUT
	bBusy : BOOL; // Do not change. Used by server to find out if the job is finished
	
	// List of OutputArguments for OPC UA method, may be customized
	State : BOOL; // Abgeschlossener MethodCall
	MethodCall: BOOL; //Input Recall
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[callCounterCheckState := callCounterCheckState + 1;
IF NOT jobFinished THEN
	bBusy := TRUE; // job is not finished yet
	CheckState := 0; // no error
ELSE
	bBusy := FALSE; // job is finished
	CheckState := 0; // done, no error occured during execution (OPC UA StatusCode "GOOD")
	jobFinished := FALSE;
	State := ResetMethodCall;
	MethodCall := MethodCall_SecuringProcess;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{4a4d1364-afb9-4324-a632-f637c79ad412}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable' := '1'}
METHOD Start : HRESULT
VAR_INPUT
	// List of InputArguments for OPC UA method, may be customized
	MethodCall : BOOL; // some description
	Securing_Time : TIME;
	SecuringProcessing_Time : TIME;
END_VAR
VAR_OUTPUT
	hdl : UDINT; // Do not change, used by server.
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[callCounterStart := callCounterStart + 1;

MethodCall_SecuringProcess := MethodCall;
SecuringTime := Securing_Time;
SecuringProcessingTime := SecuringProcessing_Time;

jobRunning := TRUE;
Start := 0; // no error occured, e.g. while parsing the input arguments (0 = OPC UA StatusCode "GOOD")]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>